### PR TITLE
Update sbt to 0.13.16 and add crossbuild to sbt 1.0.0

### PR DESCRIPTION
**Pull request by golem131**

### CODE REVIEW

**Comment by golem131** [comment]
@alkersan pls review this PR and publish new plugin

**Comment by captify-daleksandrov** [comment]
Hi @golem131. Sorry for the delay. It's been quite a while since I've used this plugin and now, unfortunately, I can't test it, because I don't have an instance with `Artifactory Pro` anymore. While all the changes look reasonable and shouldn't break the actual publish action, I'd still prefer to check it with a real Artifactory server. If you have one, could you please check?

**Comment by golem131** [comment]
@captify-daleksandrov @alkersan  I tested this PR on Artifactory. Everything works.

**Comment by golem131** [comment]
@captify-daleksandrov @alkersan anybody home?

**Comment by alkersan** [comment]
@golem131 thank you for pushing this. I've cross-published the 0.2.0 version, although it may take a while to propagate to official `sbt-plugin-releases`

**Pull request merged**
